services:
  mongodb:
    image: mongo:latest
    container_name: mongo-aeropuertos-dev
    ports:
      - "27018:27017"
    volumes:
      - mongo_data_dev:/data/db

  redis-geo:
    image: redis:alpine
    container_name: redis-geo-aeropuertos-dev
    ports:
      - "6379:6379"

  redis-pop:
    image: redis:alpine
    container_name: redis-pop-aeropuertos-dev
    ports:
      - "6380:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: api-backend-aeropuertos-dev
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/airport_db
      - REDIS_GEO_URL=redis://redis-geo:6379
      - REDIS_POP_URL=redis://redis-pop:6379
    depends_on:
      - mongodb
      - redis-geo
      - redis-pop
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/nest-cli.json:/app/nest-cli.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-aeropuertos-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api/airports
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/package.json:/app/package.json

volumes:
  mongo_data_dev:
